### PR TITLE
Adjusting logo dimensions & viewports

### PR DESCRIPTION
**Pull request by vladimyr**

### CODE REVIEW

**Review by ericbsd — APPROVED** [review]
LGTM

**Comment by vladimyr** [comment]
I'm glad to help 👍

**Comment by vladimyr** [comment]
@ericbsd OT https://ghostbsd.org is powered by Drupal 7? Source code for Drupal _theme_ is not on github I guess? It would be cool to use svg version of logo on the website.

**Comment by ericbsd** [comment]
> @ericbsd OT https://ghostbsd.org is powered by Drupal 7? Source code for Drupal _theme_ is not on github I guess? It would be cool to use svg version of logo on the website.

Yeah, you are right it is not on GitHub. I have not tried to use the SVG on it, I have no idea if the theme we use would allow that.

I hope one day to switch to a static website managed by GitHub that people can easily contribute.

**Pull request merged**
